spring:
  application:
    name: thymeleaf-crud
  datasource:
    url: jdbc:mysql://localhost:3306/my_link?useSSL=false&serverTimezone=Asia/Seoul
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 30000
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.kr.mylink.domain
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl